server:
  port: 8301
spring:
  application:
    name: borrowservice
  datasource:
    url: jdbc:mysql://@localhost:3306/db01
    username: root
    password: 1234
    driver-class-name:
eureka:
  client:
    # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      defaultZone: http://localhost:8801/eureka , http://localhost:8802/eureka
  management:
    endpoints:
      web:
        exposure:
          include: '*'
